{% set version = '3.1-9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sem
  version: {{ version|replace("-", "_") }}

source:
  fn: sem_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sem_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sem/sem_{{ version }}.tar.gz
  sha256: 4a33780202506543da85877cd2813250114420d6ec5e75457bc67477cd332cb9

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-boot
    - r-matrixcalc
    - r-mi >=0.9_99

  run:
    - r-base
    - r-mass
    - r-boot
    - r-matrixcalc
    - r-mi >=0.9_99

test:
  commands:
    - $R -e "library('sem')"  # [not win]
    - "\"%R%\" -e \"library('sem')\""  # [win]

about:
  home: http://socserv.socsci.mcmaster.ca/jfox/
  license: GPL (>= 2)
  summary: Functions for fitting general linear structural equation models (with observed and
    latent variables) using the RAM approach, and for fitting structural equations
    in observed-variable models by two-stage least squares.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
