{% set version = "3.1-11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sem
  version: {{ version|replace("-", "_") }}

source:
  fn: sem_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sem_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sem/sem_{{ version }}.tar.gz
  sha256: 33b1ad7695db13af8cdd214f5d388db494528b433c61c7ad89970cefcc8b430e

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-boot
    - r-matrixcalc
    - r-mi >=0.9_99
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-boot
    - r-matrixcalc
    - r-mi >=0.9_99

test:
  commands:
    - $R -e "library('sem')"           # [not win]
    - "\"%R%\" -e \"library('sem')\""  # [win]

about:
  home: http://socserv.socsci.mcmaster.ca/jfox/
  license: GPL (>= 2)
  summary: Functions for fitting general linear structural equation models (with observed and latent variables) using the RAM approach, and for fitting structural equations in observed-variable models by two-stage least squares.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
