travis:
  secure:
    BINSTAR_TOKEN: UrJQkxscBttyq9MEdwed5Lsswvm2CuNCyJlCwmLIR62olI3G2fS/R01tpcrb1C29dbhVv3pQqKbL+MPZHmwv0wVtg3EI/9ZmfHZ6b1SvcrDJ0elE0OwOSNimsm2n0VwjrIjFuc3PtRGezBktXdVvhb96RJ6kawv3kA4BMs1U6PdkPHiEzD3ltFxAuJyG+XuJ3lypOSoJQVdzou1VRHFYmAwKit3l5gMGYRy8mxcV1SrsUBMLCIHQJffnQVR7mVNytgIrBYXC0cAisqGDSlKx6KIYYbgaTWyJT+3c/VoQiApu246is1IowF9vHlpnQXHfL05nIWT2LlU+eJgjpKBabtfXuKwBYqYq5ubFZDzuQ7yIyfQfFIlR9VcUDuVVry+zAHyrDb/VC2FkvmEdJRKgyQUeEhtOJ4gUG0UJK7pmuPpd4dZCm1bUOgRZR/fGwUS0eC44JNCOzKWEma0j2K1dRU0mQPNCmWg6V+kuZdUrsbZuAVjLjuMhwsa3z0DUcay5DZcGPuYgDWO8Mful5MVBTQIPhH/v6nfitcDpvSHdFzSa4+PVzvccsjfpxhHXrohvJevbeuWohTXNC4yXQ/uAHb7MvzBOCCMEcn9YdM94RJYMz1Dd7ev6z0Q94agSo95Z++QrMzOA5B1PpEINDk6aF7zOS89XlVTLvdiJdn5M9Kg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
