appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Dr/p8GLhDsaw0URSofNu6YRa7KTwwT3E9ua3VmRWCJ5WPnEcCGG6UsWe6neaVcohd3mIftvBWXkxgFDHIoghZ6JPC/MUWBKlv831ddKD0SxsbYkXHB1Hi+0aOufwZsP3v4t/vTBNWXdTmtCfesv7tt5CHmuLdzr6rmplgpWQuh4IcJwJpddByq5jZOz8A/Nj0dfdq6ssuZ9cANKJNFjG6+l1vwMq7jcI4Igr6/bMh30Sv0vvN8nxh5ga9w6/rj8Zb4W8XlFurB+sf4yacoqhULnsyjwm3sDw0wkjuQ5m/mq/s60miRuFTN1QrDggQvKF8/a6QPALZvGfujt8zV6geGLYyD4WJ8E8upV5w77JFEbSXRO1XEosSrA7Gx6cfRhRfXu9HzkSgwtCuLiRay2zsp8+PZ3HfbVA2Rs2jGn+30Lel4UF9jwcjBYtmxLLIu3EDtZyhn3zW2MfoGvgDz7LT4SgmlDPq70lQKiw77v5AV6GurtpWvdwxd6t/AEsgEuXtod8iQK0HNT8Jho9cXieGyuJZOkD81ieXzsrNIPm1jfJyQSknarBjDZ6HbxL8OaBjOZPggPfzpSHa3mEbSSkgZ33NLK/9JVPgeJLy3h06E50wKXY+VOqCJPXgt9ysks2VGw4KvqRnb+RwCQZcmwwlbg021aBJJEoX5lJF9dy2VQ=}
bot:
  automerge: true
